### ISSUE TITLE
set header path,andr drag RenderVC .a into a project run

### ISSUE THREAD

**Issue by shaojiankui** [OGStudio/openscenegraph-cross-platform-guide#6]
Undefined symbols for architecture arm64:
  "osgNativeLib::frame()", referenced from:
      -[RenderVC step] in RenderVC.o
  "osgNativeLib::init(int, int, float, UIView*)", referenced from:
      -[RenderVC setupWindow] in RenderVC.o
  "osgNativeLib::loadModel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      -[RenderVC loadResources] in RenderVC.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kornerr** [comment]
Hi.

As far as I can tell, this is iOS. Try to clean build directory and rebuild OpenSceneGraph.

**Comment by shaojiankui** [comment]
Why can't you give developer the compiled frameworks or  static library。OpenSceneGraph is very hard to compile by ourself。 i try many time,finaly both failure。Official Cmake tutorial configuration is not clear，not list specific items and need removed items。

**Comment by kornerr** [comment]
OpenSceneGraph building process for non-desktop platforms is not intuitive, I agree.

However, distributing OpenSceneGraph binaries is not really a way to go because both iOS and OpenSceneGraph are frequently updated, so one would have to spend a lot of time just to build OpenSceneGraph binaries.

What you really want, though, is a simpler way to build OpenSceneGraph for iOS. Here's a script I use to build OpenSceneGraph for iOS currently: https://github.com/OGStudio/openscenegraph-cross-platform-examples/blob/Mahjong-17/build-osg-ios
This script only builds those OpenSceneGraph libraries (targets) that I currently use. The script
should be invoked after `configuration` stage. Try it.

I used the script today to build OpenSceneGraph for iOS Simulator, worked fine for me.

**Comment by shaojiankui** [comment]
actually,the problem is configuration “https://github.com/OGStudio/openscenegraph-cross-platform-guide/tree/master/1.9.SampleUnderIOS 1.9.5. Generate Xcode project file”,Official Cmake tutorial configuration is not clear，not list specific entry items and need removed entry items or need modify entry items。 
the wrong configuration,the generate is wrong.
![dbdc59b1-82fb-4695-ac3a-5e07dbbd0401](https://user-images.githubusercontent.com/5194500/42740758-298fb43c-88de-11e8-80a6-b1b165546cca.png)

**Comment by shaojiankui** [comment]
actually,the problem is configuration,i download the source from https://github.com/openscenegraph/OpenSceneGraph, and reference “https://github.com/OGStudio/openscenegraph-cross-platform-guide/tree/master/1.9.SampleUnderIOS 1.9.5. Generate Xcode project file”,Official Cmake tutorial configuration is not clear，not list specific entry items and need removed entry items or need modify entry items。
the wrong configuration,the generate is wrong.

**Comment by shaojiankui** [comment]
,i download the source from https://github.com/openscenegraph/OpenSceneGraph,load from cmake.app, click configure an soon，click generate directly。 and run build-osg-ios。
finnal generated .dylib file。i want to get the .framework or .a file.

**Comment by kornerr** [comment]
Try to build using these instructions: https://github.com/OGStudio/openscenegraph-cross-platform-examples/tree/Mahjong-17#build-ios

You would need CMakeLists.txt in your project that looks similar to this (at least for OpenSceneGraph parts): https://github.com/OGStudio/openscenegraph-cross-platform-examples/blob/Mahjong-17/02.TextureImage/ios/CMakeLists.txt

That should work with current OpenSceneGraph fine. And you should build from command line only.
